### ISSUE TITLE
Cannot connect to private network

### ISSUE THREAD

**Issue by Sypheos** [TheThingsNetwork/node-app-sdk#84]
This a bug report when trying to connect to a private network. The same connection parameters are working with the go-app-sdk.

I tried the following, with and without the certificate hardcoded. 
```js
ttn.application(appID, accessKey, {
    address: "<domain>:1900",
    insecure: false,
    /* certificate: "servet.cert */
})
    .then(function (client) {
        return client.get()
    })
    .then(function (app) {
        console.log("Got app", app)
    })
    .catch(function (err) {
        console.error(err)
        process.exit(1)
    })
```
And get this:
```
{ Error: 14 UNAVAILABLE: Connect Failed
    at Object.exports.createStatusError (/home/neugdae/Workspace/TheThingsNetwork/jstest/node_modules/grpc/src/common.js:87:15)
    at Object.onReceiveStatus (/home/neugdae/Workspace/TheThingsNetwork/jstest/node_modules/grpc/src/client_interceptors.js:1214:28)
    at InterceptingListener._callNext (/home/neugdae/Workspace/TheThingsNetwork/jstest/node_modules/grpc/src/client_interceptors.js:590:42)
    at InterceptingListener.onReceiveStatus (/home/neugdae/Workspace/TheThingsNetwork/jstest/node_modules/grpc/src/client_interceptors.js:640:8)
    at callback (/home/neugdae/Workspace/TheThingsNetwork/jstest/node_modules/grpc/src/client_interceptors.js:867:24)
  code: 14,
  metadata: Metadata { _internal_repr: {} },
  details: 'Connect Failed' }
```
Though it connect to the PCN without any problem

**Comment by Sypheos** [comment]
It looks like it comes from the grpc library, something to do with ALPN. There is an alpha/beta js only library that support http2 but it currently not working with node 10.0.0, waiting on 10.1.0.

Traces obtained with GRPC_VERBOSITY=DEBUG & GRPC_TRACE=all.

First trace with example code, without manually adding the certificate: 
```
D0515 09:59:11.734379372    3446 security_handshaker.cc:127] Security handshake failed: {"created":"@1526371151.734370168","description":"Cannot check peer: missing selected ALPN property.","file":"../deps/grpc/src/core/lib/security/security_connector/security_connector.cc","file_line":769}
```

Second trace is obtained when manually adding the certificate. I assume this comes from the ssl library or the grpc not capable of handling the certificate. Maybe more env settings I am not aware of.
```
E0515 09:58:16.842018140    3407 ssl_transport_security.cc:989] Handshake failed with fatal error SSL_ERROR_SSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed.
```

Lastly I've tried with the alpha library [grpc-js-core](https://github.com/grpc/grpc-node/tree/master/packages/grpc-js-core) with `node --expose-http2`.
```
(node:4072) ExperimentalWarning: The http2 module is an experimental API.
Error TypeError: frame.getFileName is not a function
    at isInsideNodeModules (internal/util.js:360:28)
    at showFlaggedDeprecation (buffer.js:149:8)
    at new Buffer (buffer.js:174:3)
    at Array.<anonymous> (/home/neugdae/Workspace/TheThingsNetwork/node-app-sdk/node_modules/source-map-support/source-map-support.js:149:21)
    at /home/neugdae/Workspace/TheThingsNetwork/node-app-sdk/node_modules/source-map-support/source-map-support.js:53:24
    at mapSourcePosition (/home/neugdae/Workspace/TheThingsNetwork/node-app-sdk/node_modules/source-map-support/source-map-support.js:171:21)
    at wrapCallSite (/home/neugdae/Workspace/TheThingsNetwork/node-app-sdk/node_modules/source-map-support/source-map-support.js:343:20)
    at /home/neugdae/Workspace/TheThingsNetwork/node-app-sdk/node_modules/source-map-support/source-map-support.js:378:26
    at Array.map (<anonymous>)
    at Function.prepareStackTrace (/home/neugdae/Workspace/TheThingsNetwork/node-app-sdk/node_modules/source-map-support/source-map-support.js:377:24)
```

Waiting for the next version of node to update.

**Comment by Sypheos** [comment]
This doesn't concern the SDK directly but he configuration of the server/proxy that need to support http2 or have the correctly ALPN property
